# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 424267244e635a5878c215b2c15babbb1134675c9fe44927245aad2deb52b695aa3de1a6f6a091fcc3cac0f79d2b258eb58a34385aff77d89f3f250232c6afdc

test:
  secret_key_base: c3c429a5bdf4caa483ae72576b6b93da6d2aa6030f0144cf653053412b4eeb882393e60e04aa4373c44b17a4989728bb834c3a10d82c5649ea3bac9e831edc40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
